---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onetimesecret
spec:
  selector:
    matchLabels:
      run: onetimesecret
  replicas: 1
  template:
    metadata:
      labels:
        run: onetimesecret
    spec:
      containers:
      - name: onetimesecret
        image: atlantbh/onetimesecret
        ports:
        - containerPort: 7143
---
apiVersion: v1
kind: Service
metadata:
  name: onetimesecret
  labels:
    run: onetimesecret
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7143
  selector:
    run: onetimesecret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: onetimesecret
  labels:
    run: onetimesecret
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: ots.dev.k8s.abhapp.com
    http:
      paths:
        - path: /
          backend:
            serviceName: onetimesecret
            servicePort: 80
  tls:
  - hosts:
    - ots.dev.k8s.abhapp.com
    secretName: ots-dev-tls